name: python

# course
deadlines: hard
second_deadline_max: 0.5
low_demand_bonus_bound: 0.2  # optional
max_low_demand_bonus: 1.0  # optional


# checker
system: python
layout: groups
executor: sandbox


# gitlab
gitlab_url: https://gitlab.manytask.org
default_branch: main
course_group: python
public_repo: python/public-2022-fall
students_group: python/students-fall-2022
#lectures_repo: py-tasks/lectures-2022-spring
gitlab_service_username: manytask  # optional
gitlab_service_token_id: GITLAB_SERVICE_TOKEN  # optional


# manytask
manytask_url: https://py.manytask.org
manytask_token_id: TESTER_TOKEN  # optional
gitlab_api_token_id: GITLAB_API_TOKEN  # optional


# info
links:  # optional, any number of links
  "TG Channel": https://t.me/joinchat/
  "TG Chat": https://t.me/joinchat/
  "LMS": https://lk.yandexdataschool.ru/
  "Contribute Manytask": https://github.com/yandexdataschool/manytask
