- group: 5.5.group_name
  start: 10-05-2022 18:00
  deadline: 23-05-2022 23:59
  second_deadline: 23-05-2022 23:59
  enabled: true
  tasks:
    - task: task_1
      enabled: true
      score: 100
    - task: task_2
      score: 50
    - task: task_3
      score: 50

- group: 4.4.other_group_name
  start: 10-05-2022 18:00
  deadline: 23-05-2022 23:59
  second_deadline: 23-05-2022 23:59
  enabled: true
  tasks:
    - task: big_hw
      review: true
      score: 400
      marked: true
    - task: task_4
      score: 50
      scoring_func: latest

- group: 3.empty_group_name
  start: 10-05-2022 18:00
  deadline: 23-05-2022 23:59
  second_deadline: 23-05-2022 23:59
  tasks: []

- group: 2.disabled_group_name
  start: 10-05-2022 18:00
  deadline: 23-05-2022 23:59
  second_deadline: 23-05-2022 23:59
  enabled: false
  marked: true
  tasks:
    - task: task_5
      score: 50
      scoring_func: latest


- group: 1.marked_group_name
  start: 10-05-2022 18:00
  deadline: 23-05-2022 23:59
  second_deadline: 23-05-2022 23:59
  marked: true
  tasks:
    - task: task_6
      score: 20
      scoring_func: max
