variables:
  GIT_STRATEGY: clone
  REGISTRY: cr.yandex/crp9onavos88ug32d5r2/grader/py


# Testing and Grading all changed tasks
grade:
  image: $REGISTRY/testenv:latest
  tags:
    - python-public-tester
  rules:
    - if: $CI_PROJECT_NAME =~ /^public-(fall|spring)-20\d\d/
      when: never
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /contributing/ || $CI_COMMIT_BRANCH =~ /contributing/
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: on_success
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual
    - when: on_success
  script:
    - cd /opt/shad/
    - python3 -m checker grade
  timeout: 10 minutes

# Auto on Merge Requests: check current student mege requests
grade-mrs:
  image: $REGISTRY/testenv:latest
  tags:
    - python-public-tester
  rules:
    - if: $CI_PROJECT_NAME =~ /^public-(fall|spring)-20\d\d/
      when: never
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /contributing/ || $CI_COMMIT_BRANCH =~ /contributing/
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
      allow_failure: true
    - when: never
  script:
    - cd /opt/shad/
    - python3 -m checker grade-mrs
  timeout: 10 minutes

# Checking contribution to the main repo
check:
  image: $REGISTRY/testenv:latest
  tags:
    - python-public-tester
  rules:
    - if: $CI_PROJECT_NAME =~ /^public-(fall|spring)-20\d\d/
      when: never
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /contributing/ || $CI_COMMIT_BRANCH =~ /contributing/
      when: on_success
    - when: never
  script:
    - cp -R /opt/shad/tests tests/
    - python3 -m checker check --contributing
  timeout: 30 minutes
