variables:
  GIT_STRATEGY: clone
  REGISTRY: cr.yandex/crp9onavos88ug32d5r2/grader/py


stages:
  - build
  - check-tools
  - check-tasks
  - deploy
  - manual


rebuild-base-image:
  stage: build
  rules:
    - if: $TRIGGER_PAYLOAD
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: on_success
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - when: on_success
  tags:
    - python-builder
  script:
    # Note: Expected docker registry `$REGISTRY` to be already authenticated
    - echo "building base image = $REGISTRY/base-image:$CI_COMMIT_REF_NAME"
    - docker pull $REGISTRY/base-image:latest || true
    - docker pull $REGISTRY/base-image:$CI_COMMIT_REF_NAME || true
    - docker build
      --tag $REGISTRY/base-image:$CI_COMMIT_REF_NAME
      --cache-from $REGISTRY/base-image:latest
      --cache-from $REGISTRY/base-image:$CI_COMMIT_REF_NAME
      --file base.docker
      -- .
    - docker push $REGISTRY/base-image:$CI_COMMIT_REF_NAME
    # Push as latest image if master branch
    - >
      if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]; then
        echo "pushing base image = $REGISTRY/base-image:latest"
        docker tag $REGISTRY/base-image:$CI_COMMIT_REF_NAME $REGISTRY/base-image:latest
        docker push $REGISTRY/base-image:latest
      fi


check-tools-testlib:
  image: $REGISTRY/base-image:$CI_COMMIT_REF_NAME
  stage: check-tools
  rules:
    - if: $TRIGGER_PAYLOAD
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: on_success
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - when: on_success
  allow_failure: false
  tags:
    - python-private-tester
  script:
    - python3 -m pip install --editable tools/testlib
    - python3 -m flake8 tools/testlib
    - python3 -m mypy tools/testlib
    - python3 -m pytest tools/testlib --cov=tools/testlib/testlib --cov-report=term-missing


check-tasks:
  image: $REGISTRY/base-image:$CI_COMMIT_REF_NAME
  stage: check-tasks
  rules:
    - if: $TRIGGER_PAYLOAD
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: on_success
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - when: on_success
  allow_failure: false
  tags:
    - python-private-tester
  script:
    - python3 -m pip install --editable tools/testlib
    - python3 -m checker check --parallelize


deploy-public:
  image: $REGISTRY/base-image:latest
  stage: deploy
  rules:
    - if: $TRIGGER_PAYLOAD
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - when: never
  tags:
    - python-private-tester
  script:
    # Note: GITLAB_API_TOKEN expected as a env secret (token with push access to public repo)
    # Copy all files to public repo
    - python3 -m checker export-public

deploy-docker:
  stage: deploy
  rules:
    - if: $TRIGGER_PAYLOAD
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - when: never
  tags:
    - docker-builder-python
  script:
    # Note: Expected docker registry `$REGISTRY` to be already authenticated
    - echo "using image = $REGISTRY/base-image:latest"
    - docker pull $REGISTRY/testenv:latest || true
    - docker build -f testenv.docker -t $REGISTRY/testenv:latest --cache-from $REGISTRY/testenv:latest .
    - docker push $REGISTRY/testenv:latest

deploy-manytask:
  image: curlimages/curl:latest
  stage: deploy
  rules:
    - if: $TRIGGER_PAYLOAD
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success
    - when: never
  tags:
    - python-private-tester
  script:
    - 'curl --fail --silent -X POST -H "Authorization: Bearer $TESTER_TOKEN"
        -H "Content-type: application/x-yaml" --data-binary "@.course.yml"
        "https://py.manytask.org/api/update_course_config"'
    - 'curl --fail --silent -X POST -H "Authorization: Bearer $TESTER_TOKEN"
        -H "Content-type: application/x-yaml" --data-binary "@.deadlines.yml"
        "https://py.manytask.org/api/update_deadlines"'
    - 'curl --fail --silent -X POST -H "Authorization: Bearer $TESTER_TOKEN"
        "https://py.manytask.org/api/update_cache"'


grade-students-mr:
  image: $REGISTRY/base-image:$CI_COMMIT_REF_NAME
  stage: manual
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - if: $TRIGGER_PAYLOAD
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - when: manual
      allow_failure: true
  tags:
    - python-private-tester
  script:
    - python3 -m checker grade-students-mrs
